name: Check Pull Request Title
description: Check that pull request titles matches a desired regular expression.
inputs:
  pattern:
    description: 'A ECMAScript supported regular expression pattern to check if a pull request title is valid.'
    required: true
runs:
  using: node12
  main: dist/index.js
